const compliments = [
    "You're an amazing person!",
    "Your smile lights up the room!",
    "You have a great sense of humor!",
    "You're incredibly thoughtful!",
    "Your creativity is inspiring!",
    "You make a difference in people's lives!",
    "Your kindness is contagious!",
    "You're a true friend!",
    "You have a heart of gold!",
    "You're a ray of sunshine!",
    "You bring out the best in everyone around you.",
    "You're a fantastic listener!",
    "You make life more fun just by being yourself.",
    "You have an infectious energy!",
    "You're wise beyond your years.",
    "You’re always thinking of new ways to be kind.",
    "You have an incredible mind!",
    "Your optimism is refreshing.",
    "You have such a unique perspective.",
    "You're stronger than you think.",
    "You’re one in a million!",
    "You have a gift for making people comfortable.",
    "You bring so much joy to those around you.",
    "You're brave and resilient.",
    "Everyday I wonder when the next time I get to hear you again",
    "Your laughter is contagious.",
    "You see beauty in the simplest things.",
    "You make others feel valued and important.",
    "You have a beautiful soul.",
    "You’re a true original!",
    "Yo"
    "You're an incredible problem-solver.",
    "You handle challenges with such grace.",
    "You bring out the best in others.",
    "You are a treasure to everyone who knows you.",
    "Your passion is so inspiring!",
    "You're incredibly thoughtful and considerate.",
    "You are wise and insightful.",
    "You make a difference with your positive attitude.",
    "You have a heart of gold.",
    "You inspire everyone around you.",
    "Your creativity is boundless!",
    "You give the best advice.",
    "You have a beautiful spirit.",
    "Your energy is magnetic!",
    "You're always so generous with your time.",
    "You bring so much happiness to those around you.",
    "You see the world in a unique way.",
    "You are a true gift to those in your life.",
    "Your confidence is inspiring!",
    "You make people feel seen and heard.",
    "You're a ray of light in a dark world.",
    "You radiate warmth and friendliness.",
    "You're always full of great ideas.",
    "You make things better just by showing up.",
    "You’re incredibly talented!",
    "You always find the silver lining.",
    "You’re a joy to be around.",
    "You're strong like a bull and kinder than an angel.",
    "You have a wonderful sense of humor.",
    "You bring out the best in people.",
    "You’re always striving to be the best you can be.",
    "Your smile is truly special.",
    "You're someone people can always rely on.",
    "You have such a kind heart.",
    "You inspire others to be their best selves.",
    "You're a bright spot in everyone's day.",
    "You are wise beyond your years.",
    "You handle everything with such grace.",
    "You are so generous with your time and energy.",
    "You’re a breath of fresh air!",
    "You have a heart full of love.",
    "You bring positivity to every room.",
    "You're thoughtful and caring.",
    "OI OI OI BAKA.",
    "You make the world a better place.",
    "You’re wonderfully unique.",
    "You give people so much joy.",
    "You’re a beautiful person inside and out.",
    "You have such an adventurous spirit!",
    "You make everything feel like an adventure.",
    "You always know how to make people laugh.",
    "You’re truly unforgettable.",
    "Your empathy is amazing.",
    "You’re incredibly thoughtful.",
    "You're wonderfully authentic.",
    "You’re a one-of-a-kind friend.",
    "You’re endlessly supportive.",
    "Your enthusiasm is inspiring.",
    "You make people feel valued.",
    "You light up the room.",
    "You radiate positivity.",
    "You have a peaceful presence.",
    "You’re a true friend to all.",
    "You're genuinely caring.",
    "You have a sharp and curious mind.",
    "You handle challenges like a pro.",
    "You're an inspiration to many.",
    "You are deeply compassionate.",
    "You're truly remarkable!",
    "You have a generous spirit.",
    "You have a contagious smile.",
    "You always see the good in others.",
    "You make every day brighter.",
    "You are all that and a bag of chips.",
    "You make everyone smile no matter where you go.",

    "You’re an inspiration to everyone around you.",
    "You have a heart full of compassion.",
    "You’re a beacon of hope.",
    "You're incredibly thoughtful and caring.",
    "You make everyone feel included.",
    "You have a beautiful heart.",
    "You make life so much more enjoyable.",

    "You bring a special spark to life!",

    "You're the best peach.",

];

function generateCompliment() {
    const randomIndex = Math.floor(Math.random() * compliments.length);
    document.getElementById("compliment").innerText = compliments[randomIndex];
}
